export type BeatCategory =
  | 'boom-bap'
  | 'trap'
  | 'jazz'
  | 'lo-fi'
  | 'drill'
  | 'other';

export type Beat = {
  id: string;
  src: string;
  title: string;
  bpm: number;
  barsPerLoop: number;
  startOffset?: number;  // seconds before beat 1; omit or 0 = file starts on beat 1
  category: BeatCategory;
  source?: 'youtube';    // present only for YT-downloaded beats
  previewOffset?: number; // seconds from file start to begin preview playback; defaults derived from startOffset
};

export const BEATS: Beat[] = [
  {
    id: 'criminal',
    src: '/beats/(FREE) Freestyle Boom Bap Beat ｜ ＂Criminal＂ ｜ Old School Hip Hop Beat ｜ Rap Instrumental.mp3',
    title: 'Criminal',
    bpm: 95,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'nobility',
    src: '/beats/(FREE) J Cole Freestyle Boom Bap type beat ＂Nobility＂ 2021.mp3',
    title: 'Nobility',
    bpm: 83,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'lofi-90s-freestyle',
    src: "/beats/(FREE) Lofi Type Beat - 90's Freestyle (prod. Yusei).mp3",
    title: "90s Lo-Fi",
    bpm: 72.5,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'lo-fi',
  },
  {
    id: 'low-trumpet',
    src: '/beats/(FREE) MF DOOM x Joey Bada$$ x 90s Boom Bap Type Beat - ＂Low TrumpetL＂.mp3',
    title: 'Low Trumpet',
    bpm: 93.1,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'cypher',
    src: '/beats/(FREE) Rap Beat - Cypher ｜ Old School Freestyle Boom Bap Type Beat.mp3',
    title: 'Cypher',
    bpm: 91,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'vandals',
    src: '/beats/(FREE) VANDALS - 90s boom bap type beat ｜ Funky Old school Freestyle Rap Beat.mp3',
    title: 'Vandals',
    bpm: 102,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'hard-beat',
    src: '/beats/(FREE) hard beat ｜ instrumental hip hop.mp3',
    title: 'Hard Beat',
    bpm: 89.7,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'the-supply',
    src: '/beats/(free) 90s Old School Boom Bap type beat x Freestyle Hip hop instrumental ｜ ＂The Supply＂.mp3',
    title: 'The Supply',
    bpm: 87,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'base-de-rap',
    src: "/beats/Base De Rap Old Piano - Hip Hop Instrumental - Old School Boom bap 90's Beat (FREE).mp3",
    title: 'Base De Rap',
    bpm: 80,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'bang-bang',
    src: '/beats/Dr. Dre - Bang Bang (Instrumental).mp3',
    title: 'Bang Bang',
    bpm: 95.4,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'cutthroat',
    src: '/beats/FREE Old School Dark Rap Beat ⧸ Cutthroat (Prod. By Syndrome).mp3',
    title: 'Cutthroat',
    bpm: 80,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'cash-is-king',
    src: '/beats/Freestyle Type Beat - ＂CASH IS KING＂ ｜ Rap Instrumental 2026 ｜ Rap Beats.mp3',
    title: 'Cash Is King',
    bpm: 85,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'off-the-chain',
    src: '/beats/Freestyle Type Beat - ＂OFF THE CHAIN＂ ｜ Rap Instrumental 2026 ｜ Rap Beats.mp3',
    title: 'Off The Chain',
    bpm: 84.2,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'passion-and-pain',
    src: '/beats/Freestyle Type Beat - ＂PASSION & PAIN＂ ｜ Rap Instrumental 2026 ｜ Rap Beats.mp3',
    title: 'Passion & Pain',
    bpm: 85,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'so-many-tears',
    src: '/beats/Freestyle Type Beat - ＂SO MANY TEARS＂ ｜ Rap Instrumental 2026 ｜ Rap Beats.mp3',
    title: 'So Many Tears',
    bpm: 84.2,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'bow-down',
    src: '/beats/Ice Cube - Bow Down - Instrumental.mp3',
    title: 'Bow Down',
    bpm: 92.9,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'bigger-purpose',
    src: '/beats/J COLE TYPE BEAT - ＂BIGGER PURPOSE (FREESTYLE)＂.mp3',
    title: 'Bigger Purpose',
    bpm: 84.8,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'heaven-or-hell',
    src: '/beats/J COLE TYPE BEAT - ＂HEAVEN OR HELL＂ (FREESTYLE).mp3',
    title: 'Heaven Or Hell',
    bpm: 77,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'miles-to-go',
    src: '/beats/J COLE TYPE BEAT - ＂MILES TO GO＂ (FREESTYLE).mp3',
    title: 'Miles To Go',
    bpm: 79.6,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'this-aint-luck',
    src: "/beats/J COLE TYPE BEAT - ＂THIS AIN’T LUCK＂ (FREESTYLE).mp3",
    title: "This Ain't Luck",
    bpm: 80,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'nas-is-like',
    src: '/beats/Nas - Nas Is Like (Instrumental) - HQ.mp3',
    title: 'Nas Is Like',
    bpm: 94.5,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'warning',
    src: '/beats/The Notorious B.I.G. - Warning (Instrumental) [TRACK 4].mp3',
    title: 'Warning',
    bpm: 85,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'no-rules',
    src: '/beats/[FREE] 90s OldSchool Boom Bap Dark Hip Hop Instrumental Beat  - No Rules.mp3',
    title: 'No Rules',
    bpm: 84,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'knowledge',
    src: '/beats/[FREE] Abstract Rap Beat ⧸⧸ Knowledge.mp3',
    title: 'Knowledge',
    bpm: 104,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'easy',
    src: '/beats/[FREE] Freestyle Type Beat - ＂EASY＂ ｜ Free Type Beat ｜ Freestyle Rap Trap Instrumental (HARD).mp3',
    title: 'Easy',
    bpm: 120,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'merry',
    src: '/beats/[FREE] Freestyle Type Beat - ＂MERRY＂ ｜ Free Type Beat ｜ Rap Trap Beats Instrumental (HARD).mp3',
    title: 'Merry',
    bpm: 127.2,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'nasty',
    src: '/beats/[FREE] Freestyle Type Beat - ＂NASTY＂ ｜ Free Type Beat ｜ Rap Trap Beats Instrumental (HARD).mp3',
    title: 'Nasty',
    bpm: 78,
    barsPerLoop: 32,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'cashout',
    src: "/beats/[FREE] HARD FAST CYPHER TYPE BEAT 'CASHOUT' Booming Trap Type Beat ｜ Retnik Beats.mp3",
    title: 'Cashout',
    bpm: 81.1,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'one-day',
    src: "/beats/[FREE] Hard 90 BPM Old School Boom Bap Type Beat - 'ONE DAY' ｜ Underground Hip hop Instrumental 2021.mp3",
    title: 'One Day',
    bpm: 90,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'oath',
    src: "/beats/[FREE] J COLE X KENDRICK LAMAR TYPE BEAT 2025 'OATH'.mp3",
    title: 'Oath',
    bpm: 75,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'thirst',
    src: '/beats/[FREE] KENDRICK LAMAR X JAZZ TYPE BEAT - ＂THIRST＂.mp3',
    title: 'Thirst',
    bpm: 79.1,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'jazz',
  },
  {
    id: 'no-joke',
    src: '/beats/[FREE] Kendrick Lamar x Cordae x Dreamville Type Beat ｜ “No Joke“.mp3',
    title: 'No Joke',
    bpm: 104.7,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'switch-up',
    src: '/beats/[FREE] Kendrick Lamar x JID Type Beat - ＂SWITCH UP＂ ｜ Hard Rap Beat.mp3',
    title: 'Switch Up',
    bpm: 79,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'bounce',
    src: '/beats/[FREE] Short Rap Freestyle Type Beat - “BOUNCE” ｜ Free Beat ｜ Rap Trap Beats Freestyle Instrumental.mp3',
    title: 'Bounce',
    bpm: 74,
    barsPerLoop: 16,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'ptit-pere',
    src: "/beats/[FREE] ＂P'tit Père＂ ｜ Instrumental Rap Old School⧸Hip Hop⧸Conscient ｜ Prod. by Superfishmann.mp3",
    title: "P'tit Père",
    bpm: 84,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'heart',
    src: '/beats/[SOLD] Epic Type Beat - ＂Heart＂ (90 BPM) ｜ Rap Trap Instrumental.mp3',
    title: 'Heart',
    bpm: 90,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'trap',
  },
  {
    id: 'pineapple',
    src: '/beats/[SOLD] Freestyle Type Beat - ＂Pineapple＂ (90 BPM) ｜ Rap Hip Hop Instrumental.mp3',
    title: 'Pineapple',
    bpm: 90,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'bliss',
    src: '/beats/bliss - lofi hip hop beat (FREE FOR PROFIT USE).mp3',
    title: 'Bliss',
    bpm: 84,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'lo-fi',
  },
  {
    id: 'cosy',
    src: '/beats/cosy - lofi type beat (FREE FOR PROFIT USE).mp3',
    title: 'Cosy',
    bpm: 75,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'lo-fi',
  },
  {
    id: 'miami-snow',
    src: '/beats/＂Miami Snow＂ - Melodic Rap Instrumental Beat 90 BPM [FREE].mp3',
    title: 'Miami Snow',
    bpm: 90,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'natural',
    src: "/beats/＂Natural＂90's Old School Instrumental Rap Hip Hop Boom Bap Beat Prod By ZAG BEATMAKER.mp3",
    title: 'Natural',
    bpm: 87.9,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
  {
    id: 'right-hand',
    src: '/beats/[FREE] Aggressive Type Beat - ＂Right Hand＂ (90 BPM).mp3',
    title: 'Right Hand',
    bpm: 90,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'other',
  },
  {
    id: 'diss-ll',
    src: '/beats/(3X BEAT SWITCH) KENDRICK LAMAR TYPE BEAT ＂DISS ll＂.mp3',
    title: 'Diss ll',
    bpm: 75.1,
    barsPerLoop: 64,
    startOffset: 0,
    category: 'boom-bap',
  },
];

export function pickBeat(id: string | undefined): Beat | undefined {
  if (!id) return BEATS[0];
  return BEATS.find((b) => b.id === id); // undefined if id not found — caller decides fallback
}
